---
kind: pipeline
type: docker
name: default

steps:
  - name: chrome-build
    image: node
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npm run pack
  - name: upload
    image: plugins/s3
    settings:
      path_style: true
      endpoint: s3.dandrews.net
      bucket: faceit-elo-calculator
      access_key:
        from_secret: fec_access_key
      secret_key:
        from_secret: fec_secret_key
      source: extension*.*
      target: /chrome