---
kind: pipeline
type: docker
name: default

steps:
  - name: chrome-build
    image: node
    commands:
      - npm ci
      - npm run lint
      - npm run build
  - name: upload
    image: plugins/s3
    settings:
      bucket: faceit-elo-calculator
      access_key:
        from_secret: fec_access_key
      secret_key:
        from_secret: fec_secret_key
      source: extension.zip
      target: /chrome